services:
  mongo:
    image: mongo:6
    container_name: disaster-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  ollama:
    image: ollama/ollama:latest
    container_name: disaster-ollama
    restart: always
    ports:
      - "11434:11434"

  backend:
    build: ./backend
    container_name: disaster-backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URL=mongodb://mongo:27017/disaster
      - PORT=8081
      - OLLAMA_API_URL=http://ollama:11434
      - WEAVIATE_BASE_URL=http://weaviate:8080/v1
    depends_on:
      - mongo
      - ollama
    expose:
      - "8081"

  frontend:
    build: ./fontend-vue
    container_name: disaster-frontend
    restart: always
    env_file:
      - ./fontend-vue/.env
    environment:
      - VUE_APP_API_BASE_URL=https://sos.mfu.ac.th/api
    expose:
      - "80"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: disaster-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
 weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
    restart: always

volumes:
  mongo_data:
